-- AlterTable
ALTER TABLE "StorefrontAssortmentSettings"
ADD COLUMN "ostovarMinVcpu" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN "ostovarMinRamGb" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN "ostovarMinDiskGb" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "kahkeshanMinVcpu" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "kahkeshanMinRamGb" INTEGER NOT NULL DEFAULT 32,
ADD COLUMN "kahkeshanMinDiskGb" INTEGER NOT NULL DEFAULT 200;
