export const productFlowStates = [
  "DRAFT",
  "UNDERSTANDING_CONFIRMED",
  "REQUIREMENTS_COMPLETE",
  "RECOMMENDED",
  "PARCHIN_SELECTED",
  "DELIVERY_CONFIGURED",
  "QUOTED",
  "AUTH_REQUIRED",
  "AWAITING_PAYMENT",
  "PAID",
  "PROVISION_APPROVED",
  "PROVISIONING_SUBMITTED",
  "PROVISIONING",
  "HEALTH_CHECKING",
  "WAITING_ADMIN_DELIVERY_APPROVAL",
  "DELIVERED",
  "ACTIVE",
  "QUOTE_EXPIRED",
  "PAYMENT_REVIEW",
  "PROVISIONING_RETRYABLE",
  "PROVISIONING_RECONCILING",
  "PROVISIONING_MANUAL_REVIEW",
  "HEALTH_CHECK_FAILED",
  "DELIVERY_RETRYABLE",
  "CANCELLED",
] as const;

export type ProductFlowState = (typeof productFlowStates)[number];

const transitions: Record<ProductFlowState, readonly ProductFlowState[]> = {
  DRAFT: ["UNDERSTANDING_CONFIRMED", "CANCELLED"],
  UNDERSTANDING_CONFIRMED: [
    "DRAFT",
    "REQUIREMENTS_COMPLETE",
    "CANCELLED",
  ],
  REQUIREMENTS_COMPLETE: [
    "UNDERSTANDING_CONFIRMED",
    "RECOMMENDED",
    "CANCELLED",
  ],
  RECOMMENDED: [
    "UNDERSTANDING_CONFIRMED",
    "REQUIREMENTS_COMPLETE",
    "PARCHIN_SELECTED",
    "CANCELLED",
  ],
  PARCHIN_SELECTED: [
    "UNDERSTANDING_CONFIRMED",
    "REQUIREMENTS_COMPLETE",
    "RECOMMENDED",
    "DELIVERY_CONFIGURED",
    "CANCELLED",
  ],
  DELIVERY_CONFIGURED: [
    "UNDERSTANDING_CONFIRMED",
    "PARCHIN_SELECTED",
    "REQUIREMENTS_COMPLETE",
    "QUOTED",
    "CANCELLED",
  ],
  QUOTED: [
    "AUTH_REQUIRED",
    "AWAITING_PAYMENT",
    "QUOTE_EXPIRED",
    "DELIVERY_CONFIGURED",
    "UNDERSTANDING_CONFIRMED",
    "REQUIREMENTS_COMPLETE",
    "CANCELLED",
  ],
  AUTH_REQUIRED: ["AWAITING_PAYMENT", "QUOTE_EXPIRED", "CANCELLED"],
  AWAITING_PAYMENT: [
    "PAID",
    "PAYMENT_REVIEW",
    "QUOTE_EXPIRED",
    "CANCELLED",
  ],
  PAID: [
    "PROVISION_APPROVED",
    "PROVISIONING_SUBMITTED",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  PROVISION_APPROVED: [
    "PROVISIONING_SUBMITTED",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  PROVISIONING_SUBMITTED: [
    "PROVISIONING",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
  ],
  PROVISIONING: [
    "HEALTH_CHECKING",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
  ],
  HEALTH_CHECKING: ["WAITING_ADMIN_DELIVERY_APPROVAL", "HEALTH_CHECK_FAILED"],
  WAITING_ADMIN_DELIVERY_APPROVAL: [
    "DELIVERED",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  DELIVERED: ["ACTIVE", "DELIVERY_RETRYABLE"],
  ACTIVE: [],
  QUOTE_EXPIRED: [
    "UNDERSTANDING_CONFIRMED",
    "REQUIREMENTS_COMPLETE",
    "RECOMMENDED",
    "DELIVERY_CONFIGURED",
    "CANCELLED",
  ],
  PAYMENT_REVIEW: ["AWAITING_PAYMENT", "PAID", "CANCELLED"],
  PROVISIONING_RETRYABLE: [
    "PROVISIONING_SUBMITTED",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  PROVISIONING_RECONCILING: [
    "PROVISIONING",
    "HEALTH_CHECKING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
  ],
  PROVISIONING_MANUAL_REVIEW: [
    "PROVISIONING_RECONCILING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_SUBMITTED",
    "HEALTH_CHECKING",
    "CANCELLED",
  ],
  HEALTH_CHECK_FAILED: [
    "HEALTH_CHECKING",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  DELIVERY_RETRYABLE: [
    "DELIVERED",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  CANCELLED: [],
};

export function isProductFlowState(value: unknown): value is ProductFlowState {
  return (
    typeof value === "string" &&
    (productFlowStates as readonly string[]).includes(value)
  );
}

export function canTransitionProductFlow(
  from: ProductFlowState,
  to: ProductFlowState,
): boolean {
  return transitions[from]?.includes(to) ?? false;
}

export function assertProductFlowTransition(
  from: ProductFlowState,
  to: ProductFlowState,
): void {
  if (!canTransitionProductFlow(from, to)) {
    throw new Error(`invalid_product_flow_transition:${from}:${to}`);
  }
}

export function nextProductFlowStates(
  state: ProductFlowState,
): readonly ProductFlowState[] {
  return transitions[state];
}
