export const productFlowStates = [
  "DRAFT",
  "UNDERSTANDING_CONFIRMED",
  "REQUIREMENTS_COMPLETE",
  "RECOMMENDED",
  "PARCHIN_SELECTED",
  "DELIVERY_CONFIGURED",
  "AUTH_REQUIRED",
  "AWAITING_PAYMENT",
  "PROVISIONING_SUBMITTED",
  "HEALTH_CHECKING",
  "DELIVERED",
  "QUOTE_EXPIRED",
  "PAYMENT_REVIEW",
  "PROVISIONING_RETRYABLE",
  "PROVISIONING_RECONCILING",
  "PROVISIONING_MANUAL_REVIEW",
  "HEALTH_CHECK_FAILED",
  "DELIVERY_RETRYABLE",
  "CANCELLED",
  "ENTRY",
  "DISCOVERY",
  "PROFILE_REVIEW",
  "COMPARING",
  "QUOTED",
  "CONFIGURING",
  "AUTHENTICATING",
  "CHECKOUT",
  "PAYMENT_PENDING",
  "PAID",
  "WAITING_PROVIDER_FUNDING",
  "PROVISIONING",
  "RECONCILING",
  "HEALTH_CHECK",
  "SECURE_DELIVERY",
  "ACTIVE",
  "RENEWAL_DUE",
  "SUSPENDED",
  "TERMINATED",
  "ESCALATED",
  "EXPIRED",
  "FAILED",
] as const;

export type ProductFlowState = (typeof productFlowStates)[number];

const transitions: Record<ProductFlowState, readonly ProductFlowState[]> = {
  DRAFT: ["UNDERSTANDING_CONFIRMED", "CANCELLED"],
  UNDERSTANDING_CONFIRMED: [
    "DRAFT",
    "REQUIREMENTS_COMPLETE",
    "CANCELLED",
  ],
  REQUIREMENTS_COMPLETE: [
    "UNDERSTANDING_CONFIRMED",
    "RECOMMENDED",
    "CANCELLED",
  ],
  RECOMMENDED: [
    "REQUIREMENTS_COMPLETE",
    "PARCHIN_SELECTED",
    "CANCELLED",
  ],
  PARCHIN_SELECTED: ["RECOMMENDED", "DELIVERY_CONFIGURED", "CANCELLED"],
  DELIVERY_CONFIGURED: [
    "REQUIREMENTS_COMPLETE",
    "PARCHIN_SELECTED",
    "QUOTED",
    "CANCELLED",
  ],
  AUTH_REQUIRED: ["AWAITING_PAYMENT", "QUOTE_EXPIRED", "CANCELLED"],
  AWAITING_PAYMENT: [
    "PAID",
    "PAYMENT_REVIEW",
    "QUOTE_EXPIRED",
    "CANCELLED",
  ],
  PROVISIONING_SUBMITTED: [
    "PROVISIONING",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
  ],
  HEALTH_CHECKING: ["DELIVERED", "HEALTH_CHECK_FAILED"],
  DELIVERED: ["ACTIVE", "DELIVERY_RETRYABLE"],
  QUOTE_EXPIRED: ["RECOMMENDED", "CANCELLED"],
  PAYMENT_REVIEW: ["AWAITING_PAYMENT", "PAID", "CANCELLED"],
  PROVISIONING_RETRYABLE: [
    "PROVISIONING_SUBMITTED",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  PROVISIONING_RECONCILING: [
    "PROVISIONING",
    "HEALTH_CHECKING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
  ],
  PROVISIONING_MANUAL_REVIEW: [
    "PROVISIONING_RECONCILING",
    "PROVISIONING_SUBMITTED",
    "CANCELLED",
  ],
  HEALTH_CHECK_FAILED: [
    "HEALTH_CHECKING",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  DELIVERY_RETRYABLE: [
    "DELIVERED",
    "PROVISIONING_MANUAL_REVIEW",
    "CANCELLED",
  ],
  CANCELLED: [],
  ENTRY: ["DISCOVERY"],
  DISCOVERY: ["PROFILE_REVIEW", "ESCALATED"],
  PROFILE_REVIEW: ["DISCOVERY", "COMPARING", "ESCALATED"],
  COMPARING: ["QUOTED", "PROFILE_REVIEW", "FAILED"],
  QUOTED: [
    "REQUIREMENTS_COMPLETE",
    "AUTH_REQUIRED",
    "AWAITING_PAYMENT",
    "CONFIGURING",
    "PROFILE_REVIEW",
    "EXPIRED",
    "QUOTE_EXPIRED",
  ],
  CONFIGURING: ["QUOTED", "AUTHENTICATING", "CHECKOUT", "EXPIRED"],
  AUTHENTICATING: ["CHECKOUT", "CONFIGURING", "EXPIRED"],
  CHECKOUT: ["PAYMENT_PENDING", "QUOTED", "EXPIRED"],
  PAYMENT_PENDING: ["PAID", "CHECKOUT", "FAILED", "EXPIRED"],
  PAID: [
    "PROVISIONING_SUBMITTED",
    "PROVISIONING_MANUAL_REVIEW",
    "WAITING_PROVIDER_FUNDING",
    "PROVISIONING",
  ],
  WAITING_PROVIDER_FUNDING: ["PROVISIONING", "FAILED"],
  PROVISIONING: [
    "HEALTH_CHECKING",
    "PROVISIONING_RECONCILING",
    "PROVISIONING_RETRYABLE",
    "PROVISIONING_MANUAL_REVIEW",
    "RECONCILING",
    "HEALTH_CHECK",
    "FAILED",
  ],
  RECONCILING: ["PROVISIONING", "HEALTH_CHECK", "FAILED"],
  HEALTH_CHECK: ["SECURE_DELIVERY", "PROVISIONING", "ESCALATED", "FAILED"],
  SECURE_DELIVERY: ["ACTIVE", "ESCALATED"],
  ACTIVE: ["RENEWAL_DUE", "SUSPENDED", "TERMINATED"],
  RENEWAL_DUE: ["ACTIVE", "SUSPENDED", "TERMINATED"],
  SUSPENDED: ["ACTIVE", "TERMINATED"],
  TERMINATED: [],
  ESCALATED: ["DISCOVERY", "PROFILE_REVIEW", "PROVISIONING", "HEALTH_CHECK", "FAILED"],
  EXPIRED: ["COMPARING"],
  FAILED: ["COMPARING", "CHECKOUT", "PROVISIONING", "RECONCILING", "ESCALATED"],
};

export function canTransitionProductFlow(
  from: ProductFlowState,
  to: ProductFlowState,
): boolean {
  return transitions[from].includes(to);
}

export function assertProductFlowTransition(
  from: ProductFlowState,
  to: ProductFlowState,
): void {
  if (!canTransitionProductFlow(from, to)) {
    throw new Error(`invalid_product_flow_transition:${from}:${to}`);
  }
}

export function nextProductFlowStates(state: ProductFlowState): readonly ProductFlowState[] {
  return transitions[state];
}
